### ISSUE TITLE
hyper scan out of memory bug

### ISSUE THREAD

**Issue by 21157651** [cerebuild/hyperscan-java#21]
I use "new scanner" every time , but  the memory increase step by step , at last oom . so how to close scanner. 3q

the code is flow :

public List<Match> match(Database db, String query) throws Throwable {
    Scanner scanner = new Scanner();
    scanner.allocScratch(db);
    List<Match> results = scanner.scan(db, query);
    return results;
  }

  public static EnumSet<ExpressionFlag> expressionFlags = EnumSet
          .of(ExpressionFlag.CASELESS, ExpressionFlag.UTF8, ExpressionFlag.SINGLEMATCH,
                  ExpressionFlag.MULTILINE);

  public static void main(String[] args) throws Throwable {
      LinkedList<Expression> expressions = new LinkedList<>();
      expressions.add(new Expression("song", expressionFlags));
      Database db = Database.compile(expressions);
      whiile(true) {
          match(db,"xxx");
     }
}

**Comment by gliwka** [comment]
Hi @21157651,

thanks for the report.

Currently, there's no close method on the Scanner class, because usually you only create one Scanner instance for each Thread and keep using it for the entire lifetime of the program. 

Would it be feasible to only create one scanner instance for each thread and keep using it forever? The allocScratch method also needs to be called only when you scan using a Database the first time, after that you should only call it again when you scan using a different database. Doing otherwise incures a performance penalty.

So in your example this could look like this:

```java
public List match(Scanner scanner, Database db, String query) throws Throwable {
 List results = scanner.scan(db, query);
 return results;
}

public static EnumSet expressionFlags = EnumSet
 .of(ExpressionFlag.CASELESS, ExpressionFlag.UTF8, ExpressionFlag.SINGLEMATCH,
  ExpressionFlag.MULTILINE);

public static void main(String[] args) throws Throwable {
 LinkedList expressions = new LinkedList < > ();
 expressions.add(new Expression("song", expressionFlags));
 Database db = Database.compile(expressions);
 Scanner scanner = new Scanner();
 scanner.allocScratch(db);

 while(true) {
  match(scanner, db, "xxx");
 }
}
```

I hope this helps? In case you have any questions or a different use case, just reply to this issue with some more details and we can sort it out together.

Best,
Matthias

**Comment by 21157651** [comment]
could you support a close method for database and scanner? Beacause not every thread run all the entire lifetime of the program.The memory leak will cause a big trouble for stable multi thread's program!

**Comment by gliwka** [comment]
Sure, I'm already on it.

Just wanted to point out it incurs a performance penalty creating a new scanner instance each time.

**Comment by 21157651** [comment]
ok, thank you!

**Comment by gliwka** [comment]
I've implemented the Closeable inteface on the Scanner and Databasse classes. It's now on master branch and will be part of the next release. If you need this functionality with the current release, you can also call finalize(). It will have the same effect.

Please reopen this bug in case you have any more questions. 

PS: You can check out [this](https://01org.github.io/hyperscan/dev-reference/performance.html) to learn more about hyperscan performance.

**Comment by 21157651** [comment]
the master closeable inteface doesn't work . The memory leak  cann't stop by close method
